#!/bin/bash

export RAILS_ENV=development

export RUBY_VERSION=2.6.2
export GALORE_PATH="$(cd $(dirname "$0") && cd ../galore && pwd)"
export GA_PATH="$(dirname "$0")"

function run_cmd(){
  bash -l -c "$1"
}

function ask(){
  while true; do
    read -p "$1 [$2] (y/n)?" yn
    case $yn in
        [Yy]* ) run_cmd $2; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
  done
}

echo 'Kill Sunspot solr process...'
kill $(ps aux | grep 'sunspot' | awk '{print $2}')

ask 'Are you want to reconfigure SOLR?', "$GA_PATH/configure"

cd $GALORE_PATH

if which rbenv
then
  echo 'rbenv found, no action needed'
elif which rvm
then
  run_cmd "rvm use ${RUBY_VERSION}"
  run_cmd "ruby --version"
else
  echo 'Please install rbenv or rvm'
  exit 1
fi

echo 'starting SOLR...'
run_cmd "bundle exec rake sunspot:solr:start"

echo 'Sleeping, 5 sec...'
sleep 5

echo 'REINDEX solr...'
ask 'Are you want to reindex?', 'bundle exec rake sunspot:solr:reindex'
