#!/bin/bash

export RAILS_ENV=test

export RUBY_VERSION=2.6.2
export GALORE_PATH="$(cd $(dirname "$0") && cd ../galore && pwd)"
export GA_PATH="$(dirname "$0")"

function run_cmd(){
  bash -l -c "$1"
}

function ask(){
  while true; do
    read -p "$1 [$2] (y/n)?" yn
    case $yn in
        [Yy]* ) run_cmd $2; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
  done
}

echo 'Kill Sunspot solr process...'
kill $(ps aux | grep 'sunspot' | awk '{print $2}')


ask 'Are you want to reconfigure SOLR?', "$GA_PATH/configure"

cd $GALORE_PATH

if which rbenv
then
  echo 'rbenv found, no action needed'
elif which rvm
then
  run_cmd "rvm use ${RUBY_VERSION}"
  run_cmd "ruby --version"
else
  echo 'Please install rbenv or rvm'
  exit 1
fi

echo 'DB Setup...'
run_cmd "bundle exec rake db:setup"

echo 'starting SOLR...'
run_cmd "bundle exec rake sunspot:solr:start"

echo 'Wait for SOLR start...'
sleep 5

echo 'REINDEX solr...'
run_cmd "bundle exec rake sunspot:solr:reindex"

# INFO: Tests
echo '***** CONTROLLERS *****'
run_cmd "rails test test/controllers/**/*_test.rb"

echo '***** DATABASE *****'
run_cmd "rails test test/db/**/*_test.rb"

echo '***** HELPERS *****'
run_cmd "rails test test/helpers/**/*_test.rb"

echo '***** JOBS *****'
run_cmd "rails test test/jobs/**/*_test.rb"

echo '***** LOGGERS *****'
run_cmd "rails test test/loggers/**/*_test.rb"

echo '***** MAILERS *****'
run_cmd "rails test test/mailers/**/*_test.rb"

echo '***** MODELS *****'
run_cmd "rails test test/models/**/*_test.rb"

echo '***** NOTIFIERS *****'
run_cmd "rails test test/notifiers/**/*_test.rb"

echo '***** SERVICES *****'
run_cmd "rails test test/services/**/*_test.rb"

echo '***** SYSTEM *****'
run_cmd "rails test test/system/**/*_test.rb"
